*** Starting uWSGI 2.0.13.1 (64bit) on [Fri Sep 23 16:18:24 2016] ***
compiled with version: 5.4.0 on 23 September 2016 15:16:05
os: CYGWIN_NT-6.1-2.5.1(0.297/5/3) 2016-04-21 22:14
nodename: STM-PC-108
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /cygdrive/d/coblan/web/first/deploy
writing pidfile to /pypro/first/run/first.pid
detected binary path: /usr/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /pypro/first/src
your memory page size is 4096 bytes
detected max file descriptor number: 256
lock engine: windows mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /pypro/first/run/first.sock fd 3
Python version: 2.7.10 (default, Jun  1 2015, 18:05:38)  [GCC 4.9.2]
Set PythonHome to /cygdrive/d/ve/dj19
ImportError: No module named site
*** Starting uWSGI 2.0.13.1 (64bit) on [Fri Sep 23 16:20:28 2016] ***
compiled with version: 5.4.0 on 23 September 2016 15:16:05
os: CYGWIN_NT-6.1-2.5.1(0.297/5/3) 2016-04-21 22:14
nodename: STM-PC-108
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /cygdrive/d/coblan/web/first/deploy
writing pidfile to /pypro/first/run/first.pid
detected binary path: /usr/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /pypro/first/src
your memory page size is 4096 bytes
detected max file descriptor number: 256
lock engine: windows mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /pypro/first/run/first.sock fd 3
Python version: 2.7.10 (default, Jun  1 2015, 18:05:38)  [GCC 4.9.2]
Set PythonHome to /cygdrive/d/ve/dj19/Scripts
ImportError: No module named site
*** Starting uWSGI 2.0.13.1 (64bit) on [Fri Sep 23 16:43:27 2016] ***
compiled with version: 5.4.0 on 23 September 2016 15:16:05
os: CYGWIN_NT-6.1-2.5.1(0.297/5/3) 2016-04-21 22:14
nodename: STM-PC-108
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /cygdrive/d/coblan/web/first/deploy
writing pidfile to /pypro/first/run/first.pid
detected binary path: /usr/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /pypro/first/src
your memory page size is 4096 bytes
detected max file descriptor number: 256
lock engine: windows mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /pypro/first/run/first.sock fd 3
Python version: 2.7.10 (default, Jun  1 2015, 18:05:38)  [GCC 4.9.2]
Set PythonHome to /cygdrive/d/ve/dj19/Scripts
ImportError: No module named site
*** Starting uWSGI 2.0.13.1 (64bit) on [Fri Sep 23 16:44:19 2016] ***
compiled with version: 5.4.0 on 23 September 2016 15:16:05
os: CYGWIN_NT-6.1-2.5.1(0.297/5/3) 2016-04-21 22:14
nodename: STM-PC-108
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /cygdrive/d/coblan/web/first/deploy
writing pidfile to /pypro/first/run/first.pid
detected binary path: /usr/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /pypro/first/src
your memory page size is 4096 bytes
detected max file descriptor number: 256
lock engine: windows mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /pypro/first/run/first.sock fd 3
Python version: 2.7.10 (default, Jun  1 2015, 18:05:38)  [GCC 4.9.2]
Set PythonHome to /cygdrive/d/ve/cyg/dj19/
Python main interpreter initialized at 0x600079ca0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 404760 bytes (395 KB) for 4 cores
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "/pypro/first/src/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/cygdrive/d/ve/cyg/dj19/lib/python2.7/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup()
  File "/cygdrive/d/ve/cyg/dj19/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/cygdrive/d/ve/cyg/dj19/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/cygdrive/d/ve/cyg/dj19/lib/python2.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named ws4redis
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 25752)
spawned uWSGI worker 1 (pid: 7984, cores: 1)
spawned uWSGI worker 2 (pid: 22968, cores: 1)
spawned uWSGI worker 3 (pid: 9348, cores: 1)
spawned uWSGI worker 4 (pid: 3544, cores: 1)
unable to stat() /pypro/first/run/first.reload, events will be triggered as soon as the file is created
Fri Sep 23 08:53:10 2016 - uWSGI worker 3 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Fri Sep 23 08:53:10 2016 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Fri Sep 23 08:53:10 2016 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Fri Sep 23 08:53:10 2016 - uWSGI worker 4 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.13.1 (64bit) on [Fri Sep 23 16:54:47 2016] ***
compiled with version: 5.4.0 on 23 September 2016 15:16:05
os: CYGWIN_NT-6.1-2.5.1(0.297/5/3) 2016-04-21 22:14
nodename: STM-PC-108
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /cygdrive/d/coblan/web/first/deploy
writing pidfile to /pypro/first/run/first.pid
detected binary path: /usr/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /pypro/first/src
your memory page size is 4096 bytes
detected max file descriptor number: 256
lock engine: windows mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /pypro/first/run/first.sock fd 3
Python version: 2.7.10 (default, Jun  1 2015, 18:05:38)  [GCC 4.9.2]
Set PythonHome to /cygdrive/d/ve/cyg/dj19/
Python main interpreter initialized at 0x600079ca0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 404760 bytes (395 KB) for 4 cores
*** Operational MODE: preforking ***
Traceback (most recent call last):
  File "/pypro/first/src/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/cygdrive/d/ve/cyg/dj19/lib/python2.7/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup()
  File "/cygdrive/d/ve/cyg/dj19/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/cygdrive/d/ve/cyg/dj19/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/cygdrive/d/ve/cyg/dj19/lib/python2.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named ws4redis
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 18500)
spawned uWSGI worker 1 (pid: 9584, cores: 1)
spawned uWSGI worker 2 (pid: 6340, cores: 1)
spawned uWSGI worker 3 (pid: 14444, cores: 1)
spawned uWSGI worker 4 (pid: 15604, cores: 1)
unable to stat() /pypro/first/run/first.reload, events will be triggered as soon as the file is created
--- no python application found, check your startup logs for errors ---
[pid: 15604|app: -1|req: -1/1] 127.0.0.1 () {44 vars in 789 bytes} [Fri Sep 23 08:57:44 2016] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (1 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 15604|app: -1|req: -1/2] 127.0.0.1 () {42 vars in 707 bytes} [Fri Sep 23 08:57:44 2016] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (1 switches on core 0)
Fri Sep 23 08:59:49 2016 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Fri Sep 23 08:59:49 2016 - uWSGI worker 2 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Fri Sep 23 08:59:49 2016 - uWSGI worker 4 screams: UAAAAAAH my master disconnected: i will kill myself !!!
Fri Sep 23 08:59:49 2016 - uWSGI worker 3 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.13.1 (64bit) on [Fri Sep 23 17:10:15 2016] ***
compiled with version: 5.4.0 on 23 September 2016 15:16:05
os: CYGWIN_NT-6.1-2.5.1(0.297/5/3) 2016-04-21 22:14
nodename: STM-PC-108
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /cygdrive/d/coblan/web/first/deploy
writing pidfile to /pypro/first/run/first.pid
detected binary path: /usr/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /pypro/first/src
your memory page size is 4096 bytes
detected max file descriptor number: 256
lock engine: windows mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /pypro/first/run/first.sock fd 3
Python version: 2.7.10 (default, Jun  1 2015, 18:05:38)  [GCC 4.9.2]
Set PythonHome to /cygdrive/d/ve/cyg/dj19/
Python main interpreter initialized at 0x600079ca0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 404760 bytes (395 KB) for 4 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x600079ca0 pid: 792 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 792)
spawned uWSGI worker 1 (pid: 12868, cores: 1)
spawned uWSGI worker 2 (pid: 24360, cores: 1)
spawned uWSGI worker 3 (pid: 22816, cores: 1)
spawned uWSGI worker 4 (pid: 14352, cores: 1)
unable to stat() /pypro/first/run/first.reload, events will be triggered as soon as the file is created
./urls.py:28: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got hello.views.hello). Pass the callable instead.
  url(r'^$','hello.views.hello'),

./urls.py:29: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got hello.views.talk). Pass the callable instead.
  url(r'^talk/','hello.views.talk'),

./urls.py:31: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got pagebuilder.views.build). Pass the callable instead.
  url(r'^build/','pagebuilder.views.build'),

./urls.py:32: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got pagebuilder.views.pagebuild). Pass the callable instead.
  url(r'^pagebuilder/','pagebuilder.views.pagebuild'),

./urls.py:35: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got hello.views.upload_image_demo). Pass the callable instead.
  url(r'^upload_image_demo/$','hello.views.upload_image_demo')

[pid: 22816|app: 0|req: 1/1] 127.0.0.1 () {42 vars in 758 bytes} [Fri Sep 23 09:10:26 2016] GET / => generated 3525 bytes in 600 msecs (HTTP/1.1 200) 3 headers in 102 bytes (2 switches on core 0)
Not Found: /favicon.ico
[pid: 22816|app: 0|req: 2/2] 127.0.0.1 () {42 vars in 707 bytes} [Fri Sep 23 09:10:27 2016] GET /favicon.ico => generated 3174 bytes in 7 msecs (HTTP/1.1 404) 2 headers in 80 bytes (2 switches on core 0)
./urls.py:28: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got hello.views.hello). Pass the callable instead.
  url(r'^$','hello.views.hello'),

./urls.py:29: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got hello.views.talk). Pass the callable instead.
  url(r'^talk/','hello.views.talk'),

./urls.py:31: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got pagebuilder.views.build). Pass the callable instead.
  url(r'^build/','pagebuilder.views.build'),

./urls.py:32: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got pagebuilder.views.pagebuild). Pass the callable instead.
  url(r'^pagebuilder/','pagebuilder.views.pagebuild'),

./urls.py:35: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got hello.views.upload_image_demo). Pass the callable instead.
  url(r'^upload_image_demo/$','hello.views.upload_image_demo')

Not Found: /share
[pid: 24360|app: 0|req: 1/3] 127.0.0.1 () {44 vars in 801 bytes} [Fri Sep 23 09:10:31 2016] GET /share => generated 0 bytes in 148 msecs (HTTP/1.1 301) 2 headers in 93 bytes (2 switches on core 0)
./urls.py:28: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got hello.views.hello). Pass the callable instead.
  url(r'^$','hello.views.hello'),

./urls.py:29: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got hello.views.talk). Pass the callable instead.
  url(r'^talk/','hello.views.talk'),

./urls.py:31: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got pagebuilder.views.build). Pass the callable instead.
  url(r'^build/','pagebuilder.views.build'),

./urls.py:32: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got pagebuilder.views.pagebuild). Pass the callable instead.
  url(r'^pagebuilder/','pagebuilder.views.pagebuild'),

./urls.py:35: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got hello.views.upload_image_demo). Pass the callable instead.
  url(r'^upload_image_demo/$','hello.views.upload_image_demo')

[pid: 14352|app: 0|req: 1/4] 127.0.0.1 () {44 vars in 803 bytes} [Fri Sep 23 09:10:31 2016] GET /share/ => generated 16046 bytes in 196 msecs (HTTP/1.1 200) 3 headers in 102 bytes (2 switches on core 0)
[pid: 24360|app: 0|req: 2/5] 127.0.0.1 () {44 vars in 789 bytes} [Fri Sep 23 09:18:44 2016] GET / => generated 3525 bytes in 133 msecs (HTTP/1.1 200) 3 headers in 102 bytes (2 switches on core 0)
[pid: 24360|app: 0|req: 3/6] 127.0.0.1 () {50 vars in 1007 bytes} [Fri Sep 23 09:36:58 2016] POST /upload_image_demo/ => generated 62 bytes in 148 msecs (HTTP/1.1 200) 2 headers in 80 bytes (29 switches on core 0)
./urls.py:28: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got hello.views.hello). Pass the callable instead.
  url(r'^$','hello.views.hello'),

./urls.py:29: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got hello.views.talk). Pass the callable instead.
  url(r'^talk/','hello.views.talk'),

./urls.py:31: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got pagebuilder.views.build). Pass the callable instead.
  url(r'^build/','pagebuilder.views.build'),

./urls.py:32: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got pagebuilder.views.pagebuild). Pass the callable instead.
  url(r'^pagebuilder/','pagebuilder.views.pagebuild'),

./urls.py:35: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got hello.views.upload_image_demo). Pass the callable instead.
  url(r'^upload_image_demo/$','hello.views.upload_image_demo')

[pid: 12868|app: 0|req: 1/7] 127.0.0.1 () {50 vars in 1011 bytes} [Fri Sep 23 09:45:19 2016] POST /upload_image_demo/ => generated 67 bytes in 83088 msecs (HTTP/1.1 200) 2 headers in 80 bytes (1590 switches on core 0)
[pid: 24360|app: 0|req: 4/8] 127.0.0.1 () {42 vars in 758 bytes} [Fri Sep 23 09:56:49 2016] GET / => generated 3525 bytes in 92 msecs (HTTP/1.1 200) 3 headers in 102 bytes (2 switches on core 0)
[pid: 22816|app: 0|req: 3/9] 127.0.0.1 () {44 vars in 803 bytes} [Fri Sep 23 09:56:51 2016] GET /share/ => generated 16046 bytes in 82 msecs (HTTP/1.1 200) 3 headers in 102 bytes (2 switches on core 0)
